const projects = [
  {
    id: 1,
    title: "EcommerceBot AI",
    type: "E-commerce",
    year: "2024",
    lang: "React + Node.js",
    desc: "Plateforme e-commerce avec IA pour recommandations personnalisées",
    image:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop",
    technologies: ["React", "Node.js", "TensorFlow", "PostgreSQL", "Stripe"],
    github: "https://github.com/oppai-collective/ecommerce-bot",
    demo: "https://ecommerce-bot.oppai-collective.fr",
    status: "Terminé",
    featured: true,
    stats: {
      stars: 147,
      forks: 23,
      downloads: "2.1k",
      views: "8.5k",
    },
    duration: "4 mois",
    team: "3 devs",
    category: "web",
    difficulty: "Expert",
  },
  {
    id: 2,
    title: "CryptoTracker Pro",
    type: "Finance",
    year: "2024",
    lang: "React Native",
    desc: "Application mobile de tracking crypto avec alertes en temps réel",
    image:
      "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=300&fit=crop",
    technologies: ["React Native", "WebSocket", "Redux", "CoinGecko API"],
    github: "https://github.com/oppai-collective/crypto-tracker",
    demo: "https://apps.apple.com/crypto-tracker-pro",
    status: "En cours",
    featured: false,
    stats: {
      stars: 89,
      forks: 12,
      downloads: "1.5k",
      views: "4.2k",
    },
    duration: "6 mois",
    team: "2 devs",
    category: "mobile",
    difficulty: "Intermédiaire",
  },
  {
    id: 3,
    title: "DevOps Dashboard",
    type: "DevOps",
    year: "2023",
    lang: "Vue.js + Python",
    desc: "Dashboard de monitoring pour infrastructure cloud multi-provider",
    image:
      "https://images.unsplash.com/photo-1551808525-51a94da548ce?w=400&h=300&fit=crop",
    technologies: ["Vue.js", "Python", "Docker", "Kubernetes", "Grafana"],
    github: "https://github.com/oppai-collective/devops-dashboard",
    demo: "https://dashboard.oppai-collective.fr",
    status: "Maintenance",
    featured: true,
    stats: {
      stars: 234,
      forks: 45,
      downloads: "5.7k",
      views: "12.3k",
    },
    duration: "8 mois",
    team: "4 devs",
    category: "devops",
    difficulty: "Expert",
  },
  {
    id: 4,
    title: "AI Content Generator",
    type: "IA/ML",
    year: "2024",
    lang: "Python + FastAPI",
    desc: "Générateur de contenu alimenté par l'IA pour les créateurs",
    image:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=300&fit=crop",
    technologies: ["Python", "FastAPI", "OpenAI", "Streamlit", "MongoDB"],
    github: "https://github.com/oppai-collective/ai-content-gen",
    demo: "https://ai-gen.oppai-collective.fr",
    status: "Bêta",
    featured: false,
    stats: {
      stars: 156,
      forks: 28,
      downloads: "3.2k",
      views: "9.8k",
    },
    duration: "3 mois",
    team: "2 devs",
    category: "ai",
    difficulty: "Expert",
  },
  {
    id: 5,
    title: "Smart IoT Home",
    type: "IoT",
    year: "2023",
    lang: "React + Arduino",
    desc: "Système de maison intelligente avec contrôle via app mobile",
    image:
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop",
    technologies: ["React", "Arduino", "MQTT", "Raspberry Pi", "Flutter"],
    github: "https://github.com/oppai-collective/smart-home",
    demo: "https://smarthome.oppai-collective.fr",
    status: "Terminé",
    featured: false,
    stats: {
      stars: 78,
      forks: 15,
      downloads: "892",
      views: "3.1k",
    },
    duration: "5 mois",
    team: "3 devs",
    category: "iot",
    difficulty: "Intermédiaire",
  },
  {
    id: 6,
    title: "Blockchain Voting",
    type: "Blockchain",
    year: "2024",
    lang: "Solidity + React",
    desc: "Système de vote décentralisé basé sur la blockchain Ethereum",
    image:
      "https://images.unsplash.com/photo-1639762681057-408e52192e55?w=400&h=300&fit=crop",
    technologies: ["Solidity", "React", "Web3.js", "Ethereum", "MetaMask"],
    github: "https://github.com/oppai-collective/blockchain-voting",
    demo: "https://voting.oppai-collective.fr",
    status: "En cours",
    featured: true,
    stats: {
      stars: 203,
      forks: 67,
      downloads: "4.3k",
      views: "15.2k",
    },
    duration: "6 mois",
    team: "5 devs",
    category: "blockchain",
    difficulty: "Expert",
  },
];

export default projects;
